/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;
import javax.swing.JOptionPane;
import com.toedter.calendar.JDateChooser;

/**
 *
 * @author gabgab8608
 */
public class addinfo extends javax.swing.JFrame {
    private staff staffFrame; 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(addinfo.class.getName());

    /**
     * Creates new form addinfo
     */
   public addinfo(staff staffFrame) {
    this.staffFrame = staffFrame;
    initComponents();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 500));

        jPanel1.setLayout(null);

        jLabel1.setText("DATE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 240, 95, 30);

        jLabel2.setText("NAME:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 100, 95, 30);

        jLabel3.setText("AGE:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 140, 95, 34);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(130, 190, 280, 30);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(130, 100, 280, 31);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(130, 140, 280, 34);
        jPanel1.add(jDateChooser1);
        jDateChooser1.setBounds(130, 240, 150, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00 AM", "09:00 AM", "10:00 AM ", "11:00 AM,", "1:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(302, 242, 110, 30);

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Add Schedule");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(190, 30, 220, 30);

        jLabel5.setText("SYMPTOMS:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 190, 95, 30);

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(315, 310, 100, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed
private void updateAvailableTimeSlots() {
    java.util.Date selectedDate = jDateChooser1.getDate();
    if (selectedDate == null) return; // no date chosen yet

    // Format the selected date (same format used in the file)
    String dateStr = new java.text.SimpleDateFormat("yyyy-MM-dd").format(selectedDate);

    // All default time slots
    String[] allSlots = {
        "08:00 AM", "09:00 AM", "10:00 AM", "11:00 AM",
        "1:00 PM", "02:00 PM", "03:00 PM", "04:00 PM",
        "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM"
    };

    java.util.Set<String> takenSlots = new java.util.HashSet<>();

    // 🧾 Read the data file
    try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("data.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] parts = line.split(",");
            if (parts.length < 6) continue; // skip malformed line

            String savedSchedule = parts[5].trim(); // yyyy-MM-dd TIME
            if (savedSchedule.startsWith(dateStr)) {
                String takenTime = savedSchedule.substring(11).trim();
                takenSlots.add(takenTime);
            }
        }
    } catch (Exception e) {
        System.err.println("Error reading data.txt: " + e.getMessage());
    }

    // 🧮 Update combo box
    jComboBox1.removeAllItems();
    for (String slot : allSlots) {
        if (!takenSlots.contains(slot)) {
            jComboBox1.addItem(slot);
        }
    }

    // If all slots are taken
    if (jComboBox1.getItemCount() == 0) {
        JOptionPane.showMessageDialog(this,
            "All time slots for this date are already booked.",
            "Fully Booked",
            JOptionPane.INFORMATION_MESSAGE);
    }
}
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
        String name = jTextField2.getText().trim();
        String ageText = jTextField3.getText().trim();
        String symptoms = jTextField1.getText().trim();
        java.util.Date selectedDate = jDateChooser1.getDate();
        String timeSlot = (String) jComboBox1.getSelectedItem();
        

        // 🕒 Real-time Consultation Date & Time (when added)
       String dateEntered = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
        .format(new java.util.Date());
       String status = "Scheduled";


        // 🧩 Input validation
        if (name.isEmpty() || ageText.isEmpty() || symptoms.isEmpty() || selectedDate == null) {
            JOptionPane.showMessageDialog(this,
                    "Please fill out all fields and select a date.",
                    "Missing Information",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        int age;
        try {
            age = Integer.parseInt(ageText);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Age must be a valid number.",
                    "Invalid Input",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 🚫 Date validation (no past date)
        java.util.Date today = new java.util.Date();
        if (selectedDate.before(today)) {
            JOptionPane.showMessageDialog(this,
                    "date must be 1 day in advance",
                    "Invalid Date",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 📝 Format schedule date & time
        String scheduleDate = new java.text.SimpleDateFormat("yyyy-MM-dd").format(selectedDate);
        String scheduleDateTime = scheduleDate + " " + timeSlot;

        // 🔍 Check for duplicate date and time in existing data
        boolean duplicateFound = false;

        try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("data.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                if (parts.length >= 7) {
                    String existingScheduleDateTime = parts[5].trim(); // stored date + time
                    if (existingScheduleDateTime.equals(scheduleDateTime)) {
                        duplicateFound = true;
                        break;
                    }
                }
            }
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }

        if (duplicateFound) {
            JOptionPane.showMessageDialog(this,
                    "That date and time are already booked. Please choose another slot.",
                    "Duplicate Schedule",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        // ✅ Save to file using FileWriter
        java.io.FileWriter fw = new java.io.FileWriter("data.txt", true);
        java.io.BufferedWriter bw = new java.io.BufferedWriter(fw);
          bw.write(name + "," + age + "," + symptoms + "," + 
         dateEntered + "," + scheduleDateTime + "," + status);
bw.newLine();
bw.close();

        JOptionPane.showMessageDialog(this,
                "Patient information successfully added!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

        // 🔄 Refresh table in staffFrame
        staffFrame.loadTableData();

        // Close this window
        this.dispose();

        // 🧹 Clear fields
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField1.setText("");
        jDateChooser1.setDate(null);
        jComboBox1.setSelectedIndex(0);

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "An unexpected error occurred: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JComboBox<String> jComboBox1;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollBar jScrollBar1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
