/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import java.nio.file.*;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.JPanel;

import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author gabgab8608
 */
public class doctor extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(doctor.class.getName());
private javax.swing.JPanel queuePanel;

    /**
     * Creates new form doctor
     */
    public doctor() {
        initComponents();
         datamanagement.loadScheduleDataSorted(jTable1);
         chartmanager.showWeeklyScheduleGraph(jPanel2);
         setupPatientQueue();
      new javax.swing.Timer(10000, e -> {
        chartmanager.showWeeklyScheduleGraph(jPanel2);
        updatePatientQueue();
    }).start();
    }
    public void refreshDoctorTable() {
    datamanagement.loadScheduleDataSorted(jTable1);
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 700));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/resources/PROFILE PIC.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("DOCTOR JOVES");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log out >");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/resources/SUB LOGO.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("DOCTORS PANEL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 598, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1518, 111);

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel2.setForeground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(980, 310, 500, 340);

        jScrollPane1.setBorder(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 930, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(30, 100, 930, 510);

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(980, 110, 500, 190);

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Start Diagnostic");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(780, 620, 180, 30);

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Refresh");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 620, 140, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   loginframe log = new loginframe();
        log.setVisible(true);
        setVisible(false);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
               
    refreshDoctorTable();
    updatePatientQueue();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                     
    int selectedRow = jTable1.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a patient first.");
        return;
    }
    
    String name = jTable1.getValueAt(selectedRow, 0).toString().trim();
    String age = jTable1.getValueAt(selectedRow, 1).toString().trim();
    String symptoms = jTable1.getValueAt(selectedRow, 2).toString().trim();
    String dateEntered = jTable1.getValueAt(selectedRow, 3).toString().trim();
    String consultationDate = jTable1.getValueAt(selectedRow, 4).toString().trim();
    
    File file = new File("data.txt");
    File tempFile = new File("data_temp.txt");
    boolean updated = false;
    
    try (BufferedReader reader = new BufferedReader(new FileReader(file));
         BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))) {
        
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(",");
            
            
            // Match by name AND dateEntered (data[4] is dateEntered in file)
            if (data.length >= 6 && 
                data[0].trim().equalsIgnoreCase(name) && 
                data[3].trim().equals(dateEntered)) {
                
                data[5] = "On-Going"; // Update status
                writer.write(String.join(",", data));
                updated = true;
                System.out.println("✅ Updated record: " + String.join(",", data));
            } else {
                writer.write(line);
            }
            writer.newLine();
        }
    } catch (IOException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error updating patient status: " + e.getMessage());
        return;
    }
    
    if (!updated) {
        System.err.println("⚠️ Patient not found in file: " + name + " | dateEntered: " + dateEntered);
        JOptionPane.showMessageDialog(this, "Patient record not found in file!");
        return;
    }
    
    // File replacement
    if (file.delete()) {
        if (tempFile.renameTo(file)) {
            System.out.println("✅ data.txt updated successfully.");
        } else {
            System.err.println("⚠️ Failed to rename temp file.");
        }
    } else {
        System.err.println("⚠️ Failed to delete original file.");
    }
    
    // Refresh doctor table after update
    refreshDoctorTable();
    updatePatientQueue();
    
    // Open diagnosticpad
    diagnosticpad diag = new diagnosticpad(name, age, symptoms, consultationDate, dateEntered, this);
    diag.setVisible(true);
    diag.setLocationRelativeTo(null);
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void setupPatientQueue() {
    if (jPanel4 == null) return;
    
    jPanel4.removeAll();
    jPanel4.setLayout(new BorderLayout());
    jPanel4.setBackground(new Color(0, 102, 102)); 
    
    // Title
    JLabel title = new JLabel("NEXT PATIENTS", SwingConstants.CENTER);
    title.setFont(new Font("Segoe UI", Font.BOLD, 20));
    title.setForeground(Color.WHITE);
    title.setBorder(BorderFactory.createEmptyBorder(15, 0, 10, 0));
    jPanel4.add(title, BorderLayout.NORTH);
    
    // Queue container
    queuePanel = new javax.swing.JPanel();
    queuePanel.setLayout(new BoxLayout(queuePanel, BoxLayout.Y_AXIS));
    queuePanel.setBackground(new Color(0, 102, 102));
    queuePanel.setBorder(BorderFactory.createEmptyBorder(5, 15, 15, 15));
    
    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(queuePanel);
    scrollPane.setBorder(null);
    scrollPane.setBackground(new Color(0, 102, 102));
    scrollPane.getViewport().setBackground(new Color(0, 102, 102));
    
    jPanel4.add(scrollPane, BorderLayout.CENTER);
    
    // Load the queue
    updatePatientQueue();
    
    jPanel4.revalidate();
    jPanel4.repaint();
}

    private void updatePatientQueue() {
   if (queuePanel == null) return;

    queuePanel.removeAll();
    String today = java.time.LocalDate.now().toString(); // yyyy-MM-dd
    java.util.List<String[]> todayPatients = new java.util.ArrayList<>();

    try (BufferedReader br = new BufferedReader(new FileReader("data.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",");
            if (data.length >= 6) {
                String consultDateTime = data[4].trim(); // ✅ Date|Time at index 4
                String datePart = consultDateTime.split(" ")[0];
                String status = data[5].trim().toLowerCase(); // ✅ status at index 5

                if (datePart.equals(today) && 
                    (status.equals("scheduled") || status.equals("pending"))) {
                    todayPatients.add(data);
                }
            }
        }
    } catch (IOException e) {
        System.err.println("Error reading patient queue: " + e.getMessage());
    }

    // Sort by consultation time
    todayPatients.sort((a, b) -> {
        String timeA = a[4].substring(11); // ✅ use index 4
        String timeB = b[4].substring(11);
        return timeA.compareTo(timeB);
    });

    int count = Math.min(2, todayPatients.size());

    if (count == 0) {
        JLabel noPatients = new JLabel("No patients scheduled for today", SwingConstants.CENTER);
        noPatients.setFont(new Font("Segoe UI", Font.ITALIC, 14));
        noPatients.setForeground(Color.WHITE);
        noPatients.setAlignmentX(Component.CENTER_ALIGNMENT);
        queuePanel.add(Box.createVerticalGlue());
        queuePanel.add(noPatients);
        queuePanel.add(Box.createVerticalGlue());
    } else {
        for (int i = 0; i < count; i++) {
            String[] patient = todayPatients.get(i);
            JPanel card = createPatientCard(
                patient[0], // name
                patient[1], // age
                patient[2], // symptoms
                patient[4].substring(11) // ✅ show time part from Date|Time
            );
            queuePanel.add(card);
            if (i < count - 1) {
                queuePanel.add(Box.createRigidArea(new Dimension(0, 8)));
            }
        }
    }

    queuePanel.revalidate();
    queuePanel.repaint();
}

    private javax.swing.JPanel createPatientCard(String name, String age, String symptoms, String time) {
    javax.swing.JPanel card = new javax.swing.JPanel();
    card.setLayout(new BorderLayout(10, 5));
    card.setBackground(new Color(255, 255, 255, 255)); // Semi-transparent white
    card.setBorder(BorderFactory.createCompoundBorder(
        BorderFactory.createLineBorder(new Color(0, 82, 164), 2),
        BorderFactory.createEmptyBorder(8, 12, 8, 12)
    ));
    card.setMaximumSize(new Dimension(Integer.MAX_VALUE, 70));
    
    // Time label (left)
    JLabel timeLabel = new JLabel("🕐 " + time);
    timeLabel.setFont(new Font("Segoe UI", Font.BOLD, 14));
    timeLabel.setForeground(new Color(0, 102, 102));
    card.add(timeLabel, BorderLayout.WEST);
    
    // Patient info (center)
    javax.swing.JPanel infoPanel = new javax.swing.JPanel();
    infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
    infoPanel.setOpaque(false);
    
    JLabel nameLabel = new JLabel(name + " (" + age + ")");
    nameLabel.setFont(new Font("Segoe UI", Font.BOLD, 15));
    nameLabel.setForeground(Color.BLACK);
    
    JLabel symptomsLabel = new JLabel("Symptoms: " + symptoms);
    symptomsLabel.setFont(new Font("Segoe UI", Font.PLAIN, 12));
    symptomsLabel.setForeground(Color.DARK_GRAY);
    
    infoPanel.add(nameLabel);
    infoPanel.add(symptomsLabel);
    
    card.add(infoPanel, BorderLayout.CENTER);
    
    return card;
}
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
