/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author gabgab8608
 */
public class reschedinfo extends javax.swing.JFrame {
    
   private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelOldSched;
    private String name;
    private String age;
    private String symptoms;
    private String dateEntered;
    private String oldSchedule;
    private staff staffFrame;


    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(reschedinfo.class.getName());
    
    
public reschedinfo(String name, String age, String symptoms, String dateEntered, String oldSchedule, staff staffFrame) {
        initComponents();
        this.name = name;
        this.age = age;
        this.symptoms = symptoms;
        this.dateEntered = dateEntered;
        this.oldSchedule = oldSchedule;
        this.staffFrame = staffFrame;
    }


    /**
     * Creates new form reschedinfo
     */
    public reschedinfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        confirmedit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("RESCHEDULING");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("DATE");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("TIME");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:00 AM", "09:00 AM", "10:00 AM ", "11:00 AM,", "1:00 PM", "02:00 PM", "03:00 PM", "04:00 PM", "05:00 PM", "06:00 PM", "07:00 PM", "08:00 PM" }));

        confirmedit.setBackground(new java.awt.Color(0, 102, 102));
        confirmedit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        confirmedit.setForeground(new java.awt.Color(255, 255, 255));
        confirmedit.setText("Edit");
        confirmedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmeditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(confirmedit, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmedit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmeditActionPerformed
 try {
    // Get selected date and time
    Date selectedDate = jDateChooser1.getDate();
    String timeSlot = (String) jComboBox1.getSelectedItem();

    // Validate inputs
    if (selectedDate == null) {
        JOptionPane.showMessageDialog(this,
            "Please select a date.",
            "Missing Input",
            JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Prevent past dates
    Date today = new Date();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyyMMdd");
    if (Integer.parseInt(sdf.format(selectedDate)) < Integer.parseInt(sdf.format(today))) {
        JOptionPane.showMessageDialog(this,
            "You cannot select a past date!",
            "Invalid Date",
            JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Format new schedule
    String newDate = new SimpleDateFormat("yyyy-MM-dd").format(selectedDate);
    String newSchedule = newDate + " " + timeSlot;

    // ✅ Check if new slot is already taken (column index 4 = date|time)
    try (BufferedReader br = new BufferedReader(new FileReader("data.txt"))) {
        String line;
        while ((line = br.readLine()) != null) {
            String[] data = line.split(",", -1);
            if (data.length >= 5 && data[4].trim().equalsIgnoreCase(newSchedule)) {
                JOptionPane.showMessageDialog(this,
                    "This date and time slot is already taken!",
                    "Conflict",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
    }

    // Prepare files
    File inputFile = new File("data.txt");
    File tempFile = new File("temp.txt");

    boolean updated = false;

    // ✅ Update data.txt only (no move to history here)
    try (
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        BufferedWriter writer = new BufferedWriter(new FileWriter(tempFile))
    ) {
        String line;
        while ((line = reader.readLine()) != null) {
            String[] data = line.split(",", -1);

            // Match by name, age, and dateEntered
            if (data.length >= 6 &&
                data[0].trim().equalsIgnoreCase(name) &&
                data[1].trim().equalsIgnoreCase(age) &&
                data[3].trim().equalsIgnoreCase(dateEntered)) {

                // ✅ Build the updated line
                String updatedLine = String.join(",",
                    data[0].trim(),  // name
                    data[1].trim(),  // age
                    data[2].trim(),  // symptoms
                    data[3].trim(),  // date entered
                    newSchedule,     // updated date|time
                    "Re-scheduled"   // status
                );

                writer.write(updatedLine);
                updated = true;
            } else {
                writer.write(line);
            }
            writer.newLine();
        }
    }

    // Replace original file
    if (inputFile.delete() && tempFile.renameTo(inputFile)) {
        if (updated) {
            JOptionPane.showMessageDialog(this,
                "Patient successfully rescheduled!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);

            if (staffFrame != null) {
                staffFrame.loadTableData();
            }
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                "No matching record found to reschedule.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(this,
            "Error saving updated data file.",
            "File Error",
            JOptionPane.ERROR_MESSAGE);
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this,
        "An error occurred: " + e.getMessage(),
        "Error",
        JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
    }//GEN-LAST:event_confirmeditActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton confirmedit;
    public javax.swing.JComboBox<String> jComboBox1;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
