/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pkgfinal;
// Core Java
import java.io.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;

// Swing & AWT
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import java.awt.*;

// Calendar
import com.toedter.calendar.JDateChooser;
import java.util.Comparator;

// Charting (JFreeChart)
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.NumberAxis;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;


/**
 *
 * @author gabgab8608
 */
public class staff extends javax.swing.JFrame {
    private DefaultTableModel model;
private static final String FILE_PATH = "data.txt";
private static final String HISTORY_PATH = "history.txt";
private TableRowSorter<DefaultTableModel> historySorter;

private JLabel patientsValueLabel;
    private JLabel pendingValueLabel;
    private JLabel completedValueLabel;

    private JLabel patientsDateLabel;
    private JLabel pendingDateLabel;
    private JLabel completedDateLabel;



    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(staff.class.getName());
    
    
    

    /**
     * Creates new form staff
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CONTROLPANEL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PROMO = new javax.swing.JButton();
        schedule = new javax.swing.JButton();
        hsitory = new javax.swing.JButton();
        DASHBAORD = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        SCHEDULEPANEL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduletab = new javax.swing.JTable();
        refresh = new javax.swing.JButton();
        RESCHEDULE = new javax.swing.JButton();
        DELETE = new javax.swing.JButton();
        ADD1 = new javax.swing.JButton();
        HISTORYPANEL = new javax.swing.JPanel();
        seachfield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        detailsbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 700));
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/resources/SUB LOGO.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgfinal/resources/PROFILE PIC.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("STAFF JENNIFER");

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOG OUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        PROMO.setBackground(new java.awt.Color(0, 102, 102));
        PROMO.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PROMO.setForeground(new java.awt.Color(255, 255, 255));
        PROMO.setText("DASHBOARD");
        PROMO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PROMOActionPerformed(evt);
            }
        });

        schedule.setBackground(new java.awt.Color(0, 102, 102));
        schedule.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        schedule.setForeground(new java.awt.Color(255, 255, 255));
        schedule.setText("SCHEDULE");
        schedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scheduleActionPerformed(evt);
            }
        });

        hsitory.setBackground(new java.awt.Color(0, 102, 102));
        hsitory.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        hsitory.setForeground(new java.awt.Color(255, 255, 255));
        hsitory.setText("HISTORY");
        hsitory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hsitoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CONTROLPANELLayout = new javax.swing.GroupLayout(CONTROLPANEL);
        CONTROLPANEL.setLayout(CONTROLPANELLayout);
        CONTROLPANELLayout.setHorizontalGroup(
            CONTROLPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONTROLPANELLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PROMO, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(schedule, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(hsitory, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 359, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        CONTROLPANELLayout.setVerticalGroup(
            CONTROLPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONTROLPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(PROMO)
                .addComponent(schedule)
                .addComponent(hsitory))
        );

        getContentPane().add(CONTROLPANEL);
        CONTROLPANEL.setBounds(0, 0, 1500, 114);

        DASHBAORD.setBackground(new java.awt.Color(255, 255, 255));
        DASHBAORD.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        DASHBAORD.add(jPanel5);
        jPanel5.setBounds(40, 30, 320, 120);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );

        DASHBAORD.add(jPanel1);
        jPanel1.setBounds(40, 170, 1400, 360);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        DASHBAORD.add(jPanel6);
        jPanel6.setBounds(400, 30, 320, 120);

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        DASHBAORD.add(jPanel7);
        jPanel7.setBounds(760, 30, 320, 120);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        DASHBAORD.add(jPanel8);
        jPanel8.setBounds(1120, 30, 320, 120);

        getContentPane().add(DASHBAORD);
        DASHBAORD.setBounds(0, 110, 1500, 600);

        SCHEDULEPANEL.setLayout(null);

        jScrollPane1.setBorder(null);

        jScrollPane1.setViewportView(scheduletab);

        SCHEDULEPANEL.add(jScrollPane1);
        jScrollPane1.setBounds(30, 10, 1430, 480);

        refresh.setBackground(new java.awt.Color(0, 102, 102));
        refresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        SCHEDULEPANEL.add(refresh);
        refresh.setBounds(930, 510, 120, 30);

        RESCHEDULE.setBackground(new java.awt.Color(0, 102, 102));
        RESCHEDULE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RESCHEDULE.setForeground(new java.awt.Color(255, 255, 255));
        RESCHEDULE.setText("RESCHEDULE");
        RESCHEDULE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RESCHEDULEActionPerformed(evt);
            }
        });
        SCHEDULEPANEL.add(RESCHEDULE);
        RESCHEDULE.setBounds(1330, 510, 130, 30);

        DELETE.setBackground(new java.awt.Color(0, 102, 102));
        DELETE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DELETE.setForeground(new java.awt.Color(255, 255, 255));
        DELETE.setText("DELETE");
        DELETE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETEActionPerformed(evt);
            }
        });
        SCHEDULEPANEL.add(DELETE);
        DELETE.setBounds(1200, 510, 120, 30);

        ADD1.setBackground(new java.awt.Color(0, 102, 102));
        ADD1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ADD1.setForeground(new java.awt.Color(255, 255, 255));
        ADD1.setText("ADD");
        ADD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADD1ActionPerformed(evt);
            }
        });
        SCHEDULEPANEL.add(ADD1);
        ADD1.setBounds(1060, 510, 120, 30);

        getContentPane().add(SCHEDULEPANEL);
        SCHEDULEPANEL.setBounds(0, 110, 1500, 590);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Search");

        detailsbutton.setBackground(new java.awt.Color(0, 102, 102));
        detailsbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        detailsbutton.setForeground(new java.awt.Color(255, 255, 255));
        detailsbutton.setText("Details");
        detailsbutton.setPreferredSize(new java.awt.Dimension(1500, 700));
        detailsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HISTORYPANELLayout = new javax.swing.GroupLayout(HISTORYPANEL);
        HISTORYPANEL.setLayout(HISTORYPANELLayout);
        HISTORYPANELLayout.setHorizontalGroup(
            HISTORYPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1430, Short.MAX_VALUE)
            .addGroup(HISTORYPANELLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seachfield, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detailsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HISTORYPANELLayout.setVerticalGroup(
            HISTORYPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HISTORYPANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HISTORYPANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seachfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(detailsbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(HISTORYPANEL);
        HISTORYPANEL.setBounds(30, 120, 1430, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public staff() {
        initComponents();
        datamanagement.loadScheduleDataSorted(scheduletab); // ✅ load table when window opens
        setupDashboard(); 
        updateDashboardValues();
        createYearlyChart();
        
     
    }
   
    
    //components and loaders modular
public void loadTableData() {
    datamanagement.loadScheduleDataSorted(scheduletab);
}
public void loadHistoryData() {
   datamanagement.loadHistoryDataSorted(jTable2);
   initHistorySearchFunctionality();
}
private void initHistorySearchFunctionality() {
    DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
    historySorter = new TableRowSorter<>(model);
    jTable2.setRowSorter(historySorter);

    // 🔹 Add comparators safely for all columns
    for (int i = 0; i < jTable2.getColumnCount(); i++) {
        if (jTable2.getColumnName(i).equalsIgnoreCase("Consultation Status")) {
            // Custom comparator for Consultation Status column
            historySorter.setComparator(i, (o1, o2) -> {
                String s1 = o1 == null ? "" : o1.toString();
                String s2 = o2 == null ? "" : o2.toString();
                return Integer.compare(historyStatusRank(s1), historyStatusRank(s2));
            });
        } else {
            // Default alphabetical comparator for all other columns
            historySorter.setComparator(i, Comparator.comparing(
                    (Object o) -> o == null ? "" : o.toString(),
                    String.CASE_INSENSITIVE_ORDER
            ));
        }
    }

    // 🔹 Add live search listener
    seachfield.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
        @Override
        public void insertUpdate(javax.swing.event.DocumentEvent e) { filterHistoryTable(); }
        @Override
        public void removeUpdate(javax.swing.event.DocumentEvent e) { filterHistoryTable(); }
        @Override
        public void changedUpdate(javax.swing.event.DocumentEvent e) { filterHistoryTable(); }

        private void filterHistoryTable() {
            String text = seachfield.getText();
            if (text.trim().isEmpty()) {
                historySorter.setRowFilter(null);
            } else {
                try {
                    historySorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + text));
                } catch (java.util.regex.PatternSyntaxException ex) {
                    System.out.println("Invalid regex: " + ex.getMessage());
                    historySorter.setRowFilter(null);
                }
            }
        }
    });
}
private static int historyStatusRank(String s) {
      switch (s.toLowerCase()) {
        case "pending": return 1;
        case "on-going": return 2;
        case "completed": return 3;
        default: return 4;
    }
}
private void setupDashboard() {
    // Use constants so tweak is easy
    final Color TEAL = new Color(0, 102, 102);
    final Color GREEN = new Color(0, 153, 76); // ✅ for completed consultations
    final Color DATE_GRAY = new Color(230, 230, 230);
    final Font TITLE_FONT = new Font("Segoe UI", Font.BOLD, 16);
    final Font VALUE_FONT = new Font("Segoe UI", Font.BOLD, 32);
    final Font DATE_FONT = new Font("Segoe UI", Font.PLAIN, 12);

    if (jPanel8 != null) jPanel8.setVisible(false);

    int dashWidth = DASHBAORD.getWidth();
    if (dashWidth == 0) dashWidth = 1500;
    int cardW = 320, cardH = 120, gap = 40;
    int total = cardW * 3 + gap * 2;
    int startX = (dashWidth - total) / 2;
    int startY = 30;

    java.util.function.BiConsumer<javax.swing.JPanel, Integer> initCard = (panelRef, index) -> {
        panelRef.removeAll();

        // ✅ Set specific colors
        if (index == 2) panelRef.setBackground(GREEN); // Completed consultations
        else panelRef.setBackground(TEAL);

        panelRef.setLayout(new BorderLayout());
        panelRef.setBorder(BorderFactory.createEmptyBorder(10, 12, 10, 12));

        // Title label
        JLabel title = new JLabel(
            index == 0 ? "Patients Today" :
            (index == 1 ? "Scheduled Consultations" : "Completed Consultations"),
            SwingConstants.CENTER
        );
        title.setFont(TITLE_FONT);
        title.setForeground(Color.WHITE);

        // Value label
        JLabel value = new JLabel("0", SwingConstants.CENTER);
        value.setFont(VALUE_FONT);
        value.setForeground(Color.WHITE);

        // Date label
        String formattedDate = LocalDate.now().format(DateTimeFormatter.ofPattern("MMMM dd, yyyy", Locale.ENGLISH));
        JLabel date = new JLabel("As of " + formattedDate, SwingConstants.CENTER);
        date.setFont(DATE_FONT);
        date.setForeground(DATE_GRAY);

        // Save references
        if (index == 0) { patientsValueLabel = value; patientsDateLabel = date; }
        if (index == 1) { pendingValueLabel = value; pendingDateLabel = date; }
        if (index == 2) { completedValueLabel = value; completedDateLabel = date; }

        JPanel inner = new JPanel(new GridLayout(3, 1));
        inner.setOpaque(false);
        inner.add(title);
        inner.add(value);
        inner.add(date);

        panelRef.add(inner, BorderLayout.CENTER);
        panelRef.setBounds(startX + index * (cardW + gap), startY, cardW, cardH);
        panelRef.revalidate();
        panelRef.repaint();
    };

    initCard.accept(jPanel5, 0);
    initCard.accept(jPanel6, 1);
    initCard.accept(jPanel7, 2);

    if (jPanel1 != null) {
        jPanel1.removeAll();
        jPanel1.setLayout(new BorderLayout());
        jPanel1.setBackground(new Color(245, 245, 245));
        jPanel1.revalidate();
        jPanel1.repaint();
    }

    DASHBAORD.revalidate();
    DASHBAORD.repaint();
}


    //value component and loaders
    private void updateDashboardValues() {
        SwingUtilities.invokeLater(() -> {
            int patientsToday = computePatientsToday();
            int pending = computePendingCount();
            int completed = computeCompletedCount();

            if (patientsValueLabel != null) patientsValueLabel.setText(String.valueOf(patientsToday));
            if (pendingValueLabel != null) pendingValueLabel.setText(String.valueOf(pending));
            if (completedValueLabel != null) completedValueLabel.setText(String.valueOf(completed));
        });
    }
    private int computePatientsToday() {
         return datamanagement.countPatientsToday();
    }
    private int computePendingCount() {
        return datamanagement.countPendingConsultations();
    }
    private int computeCompletedCount() {
         return datamanagement.countCompletedConsultations();
    }
    private void createYearlyChart() {
       DefaultCategoryDataset dataset = new DefaultCategoryDataset();
// initialize months
String[] months = {"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"};
Map<Integer,Integer> counts = new LinkedHashMap<>();
for (int m = 1; m <= 12; m++) counts.put(m, 0);
int currentYear = LocalDate.now().getYear();

// Read data.txt and count by month for current year
try (BufferedReader br = new BufferedReader(new FileReader(FILE_PATH))) {
    String line;
    while ((line = br.readLine()) != null) {
        String[] data = line.split(",");
        if (data.length >= 5) {  // ✅ Changed from >= 6 to >= 5
            String datePart = data[4].split(" ")[0]; // ✅ Changed from data[5] to data[4] (Consultation Date|Time)
            try {
                LocalDate d = LocalDate.parse(datePart, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                if (d.getYear() == currentYear) {
                    counts.put(d.getMonthValue(), counts.getOrDefault(d.getMonthValue(), 0) + 1);
                }
            } catch (Exception ex) {
                // ignore parse errors for malformed rows
            }
        }
    }
} catch (IOException e) {
    // ignore; dataset stays zero
}

for (int m = 1; m <= 12; m++) {
    dataset.addValue(counts.get(m), "Patients", months[m-1]);
}

JFreeChart chart = ChartFactory.createBarChart(
        "Patients per Month — " + currentYear,
        "Month",
        "Count",
        dataset
        );

        // style chart
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setBackgroundPaint(Color.WHITE);
        plot.setOutlinePaint(Color.WHITE);
        plot.setDomainGridlinePaint(Color.LIGHT_GRAY);
        plot.setRangeGridlinePaint(Color.LIGHT_GRAY);
        plot.getRenderer().setSeriesPaint(0, new Color(0, 102, 102));

        NumberAxis rangeAxis = (NumberAxis) plot.getRangeAxis();
        rangeAxis.setStandardTickUnits(NumberAxis.createIntegerTickUnits());
        rangeAxis.setLowerBound(0);

        ChartPanel cpanel = new ChartPanel(chart);
        cpanel.setPopupMenu(null);
        cpanel.setMouseWheelEnabled(false);

        // place in jPanel1
        if (jPanel1 != null) {
            jPanel1.removeAll();
            jPanel1.setLayout(new BorderLayout());
            jPanel1.add(cpanel, BorderLayout.CENTER);
            jPanel1.revalidate();
            jPanel1.repaint();
        }
    }



    
    private void PROMOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PROMOActionPerformed
        //DASHBOARD
       DASHBAORD.setVisible(true);
        HISTORYPANEL.setVisible(false);
        SCHEDULEPANEL.setVisible(false);
        updateDashboardValues(); // ✅ ADD THIS - refresh stats
    createYearlyChart();
        
    }//GEN-LAST:event_PROMOActionPerformed

    private void scheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scheduleActionPerformed
      DASHBAORD.setVisible(false);
        HISTORYPANEL.setVisible(false);
        SCHEDULEPANEL.setVisible(true);
    }//GEN-LAST:event_scheduleActionPerformed

    private void hsitoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hsitoryActionPerformed
       DASHBAORD.setVisible(false);
        HISTORYPANEL.setVisible(true);
       SCHEDULEPANEL.setVisible(false);
       loadHistoryData();
    }//GEN-LAST:event_hsitoryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        loginframe log = new loginframe();
        log.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
    datamanagement.loadScheduleDataSorted(scheduletab);
    updateDashboardValues(); // ✅ ADD THIS - refresh stats
    createYearlyChart();
    }//GEN-LAST:event_refreshActionPerformed

    private void DELETEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETEActionPerformed
          int selectedRow = scheduletab.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Please select a record to delete.",
            "No Selection",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get values from table (matching loadTableDataWithSort display order)
    String name = scheduletab.getValueAt(selectedRow, 0).toString();
    String age = scheduletab.getValueAt(selectedRow, 1).toString();
    String symptoms = scheduletab.getValueAt(selectedRow, 2).toString();
    String dateEntered = scheduletab.getValueAt(selectedRow, 3).toString();  // ✅ This is Date Entered
    String consultationDateTime = scheduletab.getValueAt(selectedRow, 4).toString();  // ✅ This is Consultation Date|Time
    String consultationStatus = scheduletab.getValueAt(selectedRow, 5).toString();
    
    int confirm = JOptionPane.showConfirmDialog(this,
            "Are you sure you want to delete this record?\n\nName: " + name,
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) return;
    
    File inputFile = new File("data.txt");
    File tempFile = new File("data_temp.txt");
    File historyFile = new File("history.txt");
    boolean recordFound = false;
    
    try (
        BufferedReader reader = new BufferedReader(new FileReader(inputFile));
        BufferedWriter tempWriter = new BufferedWriter(new FileWriter(tempFile));
        BufferedWriter historyWriter = new BufferedWriter(new FileWriter(historyFile, true))
    ) {
        String currentLine;
        while ((currentLine = reader.readLine()) != null) {
            if (currentLine.trim().isEmpty()) continue;
            
            String[] data = currentLine.split(",", -1);
            if (data.length < 6) continue;
            
            // File structure: Name, Age, Symptoms, Date Entered, Consultation Date|Time, Status
            String fileName = data[0].trim();
            String fileDateEntered = data[3].trim();  // ✅ Date Entered is at index 3
            String fileConsultDateTime = data[4].trim();  // ✅ Consultation Date|Time is at index 4
            
            // ✅ Match by name AND date entered (more reliable unique identifier)
            if (fileName.equals(name) && fileDateEntered.equals(dateEntered)) {
                recordFound = true;
                
                // ✅ Write to history.txt with "Deleted" status (overwriting any existing status)
                // Only include the 6 core fields - extra fields can be added later if needed
                historyWriter.write(String.join(",", 
                    data[0].trim(),  // Name
                    data[1].trim(),  // Age
                    data[2].trim(),  // Symptoms
                    data[3].trim(),  // Date Entered
                    data[4].trim(),  // Consultation Date|Time
                    "Deleted"        // Status (overwrites "Pending" or "Scheduled")
                ));
                historyWriter.newLine();
                continue; // Skip writing to temp.txt (removes from data.txt)
            }
            
            // Keep non-deleted lines
            tempWriter.write(currentLine);
            tempWriter.newLine();
        }
        tempWriter.flush();
        historyWriter.flush();
        
    } catch (IOException e) {
        JOptionPane.showMessageDialog(this,
            "Error processing deletion: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
        return;
    }
    
    if (recordFound) {
        if (!inputFile.delete()) inputFile.deleteOnExit();
        try {
            java.nio.file.Files.move(tempFile.toPath(), inputFile.toPath(),
                    java.nio.file.StandardCopyOption.REPLACE_EXISTING);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this,
                "Failed to update data file: " + ex.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
            return;
        }
        
        JOptionPane.showMessageDialog(this,
            "Record successfully deleted and archived to history.",
            "Deleted",
            JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this,
            "No matching record found. Nothing was deleted.",
            "Not Found",
            JOptionPane.WARNING_MESSAGE);
    }
    
    // Refresh the schedule table
    DefaultTableModel model = (DefaultTableModel) scheduletab.getModel();
    model.setRowCount(0);
    datamanagement.loadScheduleDataSorted(scheduletab);
    updateDashboardValues();
    createYearlyChart();
    }//GEN-LAST:event_DELETEActionPerformed

    private void RESCHEDULEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RESCHEDULEActionPerformed
    // Check if a row is selected
    int selectedRow = scheduletab.getSelectedRow();
    
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Please select a record to reschedule.",
            "No Selection",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    // Get the selected row data
    String name = scheduletab.getValueAt(selectedRow, 0).toString();
    String age = scheduletab.getValueAt(selectedRow, 1).toString();
    String symptoms = scheduletab.getValueAt(selectedRow, 2).toString();
    String dateEntered = scheduletab.getValueAt(selectedRow, 3).toString();
    String oldSchedule = scheduletab.getValueAt(selectedRow, 4).toString();
    
    // Open reschedule dialog with ALL required parameters
    reschedinfo reschedDialog = new reschedinfo(name, age, symptoms, dateEntered, oldSchedule, this);
    reschedDialog.setVisible(true);
    reschedDialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_RESCHEDULEActionPerformed

    private void detailsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsbuttonActionPerformed
        int selectedRow = jTable2.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a patient first.");
        return;
    }

    String name = jTable2.getValueAt(selectedRow, 0).toString();
    String age = jTable2.getValueAt(selectedRow, 1).toString();
    String symptoms = jTable2.getValueAt(selectedRow, 2).toString();
    String dateEntered = jTable2.getValueAt(selectedRow, 3).toString();
    String consultDate = jTable2.getValueAt(selectedRow, 4).toString();
    String status = jTable2.getValueAt(selectedRow, 5).toString();

    // Open custom pop-up
    DetailsDialog dialog = new DetailsDialog(this, name, age, symptoms, dateEntered, consultDate, status);
    dialog.setVisible(true);
    }//GEN-LAST:event_detailsbuttonActionPerformed

    private void ADD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADD1ActionPerformed
       addinfo addDialog = new addinfo(this);
    addDialog.setVisible(true);
    addDialog.setLocationRelativeTo(this);
    }//GEN-LAST:event_ADD1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ADD1;
    public javax.swing.JPanel CONTROLPANEL;
    public javax.swing.JPanel DASHBAORD;
    public javax.swing.JButton DELETE;
    public javax.swing.JPanel HISTORYPANEL;
    public javax.swing.JButton PROMO;
    public javax.swing.JButton RESCHEDULE;
    public javax.swing.JPanel SCHEDULEPANEL;
    public javax.swing.JButton detailsbutton;
    public javax.swing.JButton hsitory;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTable2;
    public javax.swing.JButton refresh;
    public javax.swing.JButton schedule;
    public javax.swing.JTable scheduletab;
    public javax.swing.JTextField seachfield;
    // End of variables declaration//GEN-END:variables

    

}
